apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: my-app
  namespace: flux-system
resources:
  - ./my-app
  - ./my-app/base
  - ./my-app/overlays/staging
  - ./my-app/overlays/production
  - ./my-app/overlays/development
  - ./my-app/overlays/qa
  - ./my-app/overlays/test
  - ./my-app/overlays/uat
  - ./my-app/overlays/preprod
