groups:
  - name: example
    rules:
      - alert: HighCPUUsage
        expr: sum(rate(container_cpu_usage_seconds_total[5m])) by (pod) / sum(container_spec_cpu_quota) by (pod) > 0.9
        for: 1m
        labels:
          severity: critical
        annotations:
          description: "CPU usage is above 90% for more than 1 minute"
